import SceneLabChrome from "../frames/SceneLabChrome.jsx";

export const SAMPLE_CONVO = [
  { id: "m1", role: "user", content: "Create a red cube floating at position 8, 2, 8" },
  { id: "m2", role: "assistant", content: "Added a floating red cube. I created an entity with a MeshRenderer (box), a red Material, and a Transform at (8, 2, 8)." },
  { id: "m3", role: "user", content: "Make it slowly rotate and add a point light above it" },
  { id: "m4", role: "assistant", content: "Done — the cube now spins on its Y axis via a system, and I added a warm PointLight entity at (8, 4, 8). Switch to Preview to see it move." },
];

export const SAMPLE_FILES = ["package.json", "scene.json", "src/index.ts", "tsconfig.json"];

const INDEX_TS = [
  [["sl-tok-com", "// src/index.ts — generated by Scene Lab"]],
  [["sl-tok-kw", "import"], ["sl-tok-pun", " { "], ["sl-tok-ty", "engine"], ["sl-tok-pun", ", "], ["sl-tok-ty", "Transform"], ["sl-tok-pun", ", "], ["sl-tok-ty", "MeshRenderer"], ["sl-tok-pun", ", "], ["sl-tok-ty", "Material"], ["sl-tok-pun", " } "], ["sl-tok-kw", "from"], ["sl-tok-str", " '@dcl/sdk/ecs'"]],
  [["sl-tok-kw", "import"], ["sl-tok-pun", " { "], ["sl-tok-ty", "Color4"], ["sl-tok-pun", ", "], ["sl-tok-ty", "Vector3"], ["sl-tok-pun", " } "], ["sl-tok-kw", "from"], ["sl-tok-str", " '@dcl/sdk/math'"]],
  [],
  [["sl-tok-kw", "export function"], ["sl-tok-fn", " main"], ["sl-tok-pun", "() {"]],
  [["sl-tok-pun", "  "], ["sl-tok-kw", "const"], ["sl-tok-pun", " cube = "], ["sl-tok-ty", "engine"], ["sl-tok-pun", "."], ["sl-tok-fn", "addEntity"], ["sl-tok-pun", "()"]],
  [["sl-tok-pun", "  "], ["sl-tok-ty", "Transform"], ["sl-tok-pun", "."], ["sl-tok-fn", "create"], ["sl-tok-pun", "(cube, { position: "], ["sl-tok-ty", "Vector3"], ["sl-tok-pun", "."], ["sl-tok-fn", "create"], ["sl-tok-pun", "("], ["sl-tok-num", "8"], ["sl-tok-pun", ", "], ["sl-tok-num", "2"], ["sl-tok-pun", ", "], ["sl-tok-num", "8"], ["sl-tok-pun", ") })"]],
  [["sl-tok-pun", "  "], ["sl-tok-ty", "MeshRenderer"], ["sl-tok-pun", "."], ["sl-tok-fn", "setBox"], ["sl-tok-pun", "(cube)"]],
  [["sl-tok-pun", "  "], ["sl-tok-ty", "Material"], ["sl-tok-pun", "."], ["sl-tok-fn", "setPbrMaterial"], ["sl-tok-pun", "(cube, { albedoColor: "], ["sl-tok-ty", "Color4"], ["sl-tok-pun", "."], ["sl-tok-fn", "Red"], ["sl-tok-pun", "() })"]],
  [],
  [["sl-tok-pun", "  "], ["sl-tok-ty", "engine"], ["sl-tok-pun", "."], ["sl-tok-fn", "addSystem"], ["sl-tok-pun", "(("], ["sl-tok-ty", "dt"], ["sl-tok-pun", ") => {"]],
  [["sl-tok-pun", "    "], ["sl-tok-kw", "const"], ["sl-tok-pun", " t = "], ["sl-tok-ty", "Transform"], ["sl-tok-pun", "."], ["sl-tok-fn", "getMutable"], ["sl-tok-pun", "(cube)"]],
  [["sl-tok-pun", "    t.rotation = "], ["sl-tok-ty", "Quaternion"], ["sl-tok-pun", "."], ["sl-tok-fn", "multiply"], ["sl-tok-pun", "(t.rotation, spin)"]],
  [["sl-tok-pun", "  })"]],
  [["sl-tok-pun", "}"]],
];

function Code({ lines = INDEX_TS }) {
  return (
    <div className="sl-code" role="img" aria-label="src/index.ts source">
      {lines.map((toks, i) => (
        <div className="sl-code__line" key={i}>
          <span className="sl-code__gutter">{i + 1}</span>
          <span className="sl-code__src">
            {toks.map(([c, t], j) => (
              <span className={c} key={j}>{t}</span>
            ))}
            {toks.length === 0 ? " " : null}
          </span>
        </div>
      ))}
    </div>
  );
}

export function SlPromptPanel({
  messages = SAMPLE_CONVO,
  processing = false,
  viewingId = null,
  draft = "",
}) {
  const empty = messages.length === 0;
  return (
    <div className="sl-prompt">
      <div className="sl-prompt__head">
        <div>
          <h2 className="sl-prompt__title">AI Scene Generator</h2>
          <p className="sl-prompt__sub">
            Describe what you want to create ·{" "}
            <span style={{ color: "#ff2d55", fontWeight: 700 }}>
              Demo preview (sample session — not connected)
            </span>
          </p>
        </div>
        {!empty && <button type="button" className="sl-prompt__reset" disabled={processing}>Reset</button>}
      </div>

      <div className="sl-prompt__feed">
        {empty ? (
          <div className="sl-prompt__empty">
            <p>Start by describing your scene…</p>
            <p className="eg">Example: "Create a red cube floating at position 8, 2, 8"</p>
          </div>
        ) : (
          messages.map((m) => {
            const viewing = viewingId === m.id;
            return (
              <div
                key={m.id}
                className={"sl-msg " + (viewing ? "sl-msg--viewing" : m.role === "user" ? "sl-msg--user" : "sl-msg--ai")}
              >
                <div className="sl-msg__top">
                  <span className="sl-msg__role">{m.role === "user" ? "You" : "AI"}</span>
                  {m.role === "assistant" && (
                    <div className="sl-msg__acts">
                      <button type="button" className="sl-msg__btn sl-msg__btn--view" disabled={processing || viewing}>
                        {viewing ? "Viewing" : "View"}
                      </button>
                      <button type="button" className="sl-msg__btn sl-msg__btn--revert" disabled={processing}>Revert</button>
                    </div>
                  )}
                </div>
                {m.content}
              </div>
            );
          })
        )}
        {processing && <div className="sl-prompt__working">Processing…</div>}
      </div>

      <form className="sl-prompt__form" onSubmit={(e) => e.preventDefault()}>
        <div className="sl-prompt__row">
          <input
            className="sl-prompt__input"
            placeholder="Describe your scene changes…"
            defaultValue={draft}
            disabled={processing}
          />
          <button type="submit" className="sl-prompt__send" disabled={processing}>Send</button>
        </div>
      </form>
    </div>
  );
}

export function SlEditorPanel({
  mode = "code",
  activeFile = "src/index.ts",
  building = false,
  snapshot = false,
}) {
  return (
    <div className="sl-editor">
      {snapshot && (
        <div className="sl-snapbar">
          <span className="dot" />
          Viewing a previous snapshot — files are read-only. Submit a new prompt to return to the latest scene.
        </div>
      )}
      <div className="sl-editor__tabs">
        <button type="button" className={"sl-editor__tab" + (mode === "code" ? " is-active" : "")}>
          <span className="ico" aria-hidden="true">📝</span> Code
        </button>
        <button type="button" className={"sl-editor__tab" + (mode === "preview" ? " is-active" : "")}>
          <span className="ico" aria-hidden="true">👁️</span> Preview
        </button>
      </div>

      {mode === "code" ? (
        <div className="sl-editor__pane">
          <div className="sl-editor__bar">
            <div className="sl-editor__barrow">
              <span className="sl-editor__barlabel">Scene Files</span>
              <button type="button" className="sl-editor__build" disabled={building}>
                {building ? "Building…" : "Build Scene"}
              </button>
            </div>
            <div className="sl-editor__files">
              {SAMPLE_FILES.map((f) => (
                <button key={f} type="button" className={"sl-editor__file" + (f === activeFile ? " is-active" : "")}>
                  {f}
                </button>
              ))}
            </div>
          </div>
          <Code />
          <div className="sl-editor__status">
            <span>{activeFile}</span>
            <span>TYPESCRIPT</span>
          </div>
        </div>
      ) : (
        <div className="sl-preview">
          <div className="sl-preview__head">Scene Preview · Bevy Explorer</div>
          <div className="sl-preview__stage">
            <div className="sl-preview__ground" />
            <div className="sl-preview__obj" />
          </div>
          <div className="sl-preview__foot">
            <span>🎮 Decentraland Scene Preview</span>
            <span className="by">Powered by Bevy Explorer Web</span>
          </div>
        </div>
      )}
    </div>
  );
}

export default function SlStudio() {
  return (
    <SceneLabChrome
      left={<SlPromptPanel />}
      right={<SlEditorPanel mode="code" />}
    />
  );
}
